import { AuthContextProvider } from "./context/AuthContext";
import { StoreProvider } from "./context/productsContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <StoreProvider>
          <body>
            {children}
            <ToastContainer />
          </body>
        </StoreProvider>
      </AuthContextProvider>
    </html>
  );
}
